layout_spectrum: 0.9469873356191201
typography_spectrum: 0.3711993476355651
color:
  saturation: 0.09246734683411104
  brandStrength: 0.9838028231886501
  lightness: 0.06634758644230147
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  rhythmicContrast: 0.9193381918556436
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: '@360Integrity'
  google: UA-29546732-1
  facebook: null
author:
  url: 10thdot.com
  name: ''
  email: 10thdot@10thdot.com
name: 360°Integrity
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: 10th Dot
    url: 'http://www.10thdot.com'
    type: external
  - name: 360° Integrity Video
    id: f1b92b4d-19e6-4697-b0c1-ce79d77ae62a
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: ''
content: []
description: ''
purpose: []
