typography_spectrum: 0.2973154558667378
color:
  saturation: 0.7452557723241683
  brandStrength: 0.5960554113594059
  lightness: 0.06394871375883127
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  rhythmicContrast: 0.9142290546179814
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7620338991071365
analytics:
  twitter: '@360Integrity'
  google: UA-29546732-1
  facebook: null
author:
  url: 10thdot.com
  name: 10th Dot
  email: 10thdot@10thdot.com
name: 360°Integrity
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: 10th Dot
    url: 'http://www.10thdot.com'
    type: external
  - name: 360° Integrity Video
    id: f1b92b4d-19e6-4697-b0c1-ce79d77ae62a
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: ''
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FI_SANEIuH7M%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DI_SANEIuH7M&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FI_SANEIuH7M%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      datePublished: null
      isBasedOnUrl: 'https://youtu.be/I_SANEIuH7M'
      keywords:
        - duration
        - yogiraj
        - dot
        - 10th
        - views
        - bates
        - charles
        - reviews
        - film
        - movies
      related: []
      author:
        - name: 10th Dot
          url: 'https://www.youtube.com/user/10thDot'
          avatar: {}
      '@context': 'http://schema.org'
      title: Up Down Equal Circle
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=I_SANEIuH7M&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=I_SANEIuH7M&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=I_SANEIuH7M&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=I_SANEIuH7M&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=I_SANEIuH7M&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=I_SANEIuH7M'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=I_SANEIuH7M
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=I_SANEIuH7M
          package: '544007664'
          namespace: google
          type: ios
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: youtu.be
      description: Uploaded by 10th Dot on 2017-01-27.
      inLanguage: en
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ''
purpose: []
