name: 360Integrity
favicon: null
layout_spectrum: 0.4432820954825729
typography_spectrum: 0.7572
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#308519'
    - '#0c3a06'
    - '#d4eae5'
    - '#72ba61'
    - '#b2c4b6'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5450883083976805
  rhythmicContrast: 0.9268687195144594
purpose: []
